-- lua/icons/nerd.lua

return {
  ActiveLSP = '',
  ActiveTS = '',
  ArrowLeft = '',
  ArrowRight = '',
  ArrowCircleDown = '',
  ArrowCircleLeft = '',
  ArrowCircleRight = '',
  ArrowCircleUp = '',
  BoldArrowDown = '',
  BoldArrowLeft = '',
  BoldArrowRight = '',
  BoldArrowUp = '',
  BoldClose = '',
  BoldDividerLeft = '',
  BoldDividerRight = '',
  BoldLineLeft = '▎',
  BookMark = '',
  Bookmarks = '',
  BufferClose = '󰅖',
  BoxChecked = '',
  Bug = '',
  Calendar = '',
  Check = '',
  ChevronRight = '>',
  ChevronShortDown = '',
  ChevronShortLeft = '',
  ChevronShortRight = '',
  ChevronShortUp = '',
  Circle = '',
  Close = '', --  
  CloudDownload = '',
  Code = '',
  Comment = '',
  Dashboard = '',
  DapBreakpoint = '',
  DapBreakpointCondition = '',
  DapBreakpointRejected = '',
  DapLogPoint = '.>',
  DapStopped = '󰁕',
  Debugger = '',
  DebugConsole = '',
  DefaultFile = '󰈙',
  Docs = '',
  Diagnostic = '󰒡',
  DiagnosticError = '',
  DiagnosticHint = '󰌵',
  DiagnosticInfo = '󰋼',
  DiagnosticWarn = '',
  DividerLeft = '',
  DividerRight = '',
  DoubleChevronRight = '»',
  Environment = '',
  Ellipsis = '',
  EmptyFolder = '',
  EmptyFolderOpen = '',
  File = '',
  FileSymlink = '',
  Files = '',
  FindFile = '󰈞',
  FindText = '󱎸',
  Fire = '',
  Folder = '',
  FileNew = '',
  FileModified = '',
  FileReadOnly = '',
  FoldClosed = '',
  FoldOpened = '',
  FoldSeparator = ' ',
  FolderClosed = '',
  FolderEmpty = '',
  FolderOpen = '',
  FolderSymlink = '',
  Forward = '',
  Gear = '',
  Git = '󰊢',
  GitAdd = '',
  GitBranch = '',
  GitChange = '',
  GitConflict = '',
  GitDelete = '',
  GitIgnored = '◌',
  GitRenamed = '➜',
  GitSign = '▎',
  GitStaged = '✓',
  GitUnstaged = '✗',
  GitUntracked = '★',
  History = '',
  Lightbulb = '',
  LineLeft = '▏',
  LineMiddle = '│',
  List = '',
  Lock = '',
  LSPLoaded = '',
  LSPLoading1 = '',
  LSPLoading2 = '󰀚',
  LSPLoading3 = '',
  MacroRecording = '',
  NewFile = '',
  Note = '',
  Paste = '󰅌',
  Package = '', -- 󰏖
  Pencil = '',
  Plus = '',
  Project = '',
  Refresh = '',
  Run = '󰑮',
  Selected = '❯',
  Session = '󱂬',
  Sort = '󰒺',
  Spellcheck = '󰓆',
  Search = '', -- 
  SignIn = '',
  SignOut = '',
  Stacks = '',
  Scopes = '',
  Tab = '󰓩',
  TabClose = '󰅙',
  Table = '',
  Target = '󰀘',
  Telescope = '',
  Terminal = '',
  Test = '󰙨',
  Text = '',
  Tree = '',
  Triangle = '契',
  TriangleShortArrowDown = '',
  TriangleShortArrowLeft = '',
  TriangleShortArrowRight = '',
  TriangleShortArrowUp = '',
  Watches = '',
  Window = '',
  WordFile = '󰈭',
  --
  -- filetypes
  lua = '',
  markdown = '',
  ttf = '',
  robots = '󰚩',
  woff = '',
  woff2 = '',
  --
  -- diagnostics
  BoldError = '',
  Error = '',
  BoldWarning = '',
  Warning = '',
  BoldInformation = '',
  Information = '',
  BoldQuestion = '',
  Question = '',
  BoldHint = '',
  Hint = '',
  Debug = '',
  Trace = '✎',
  --
  --
  kind = {
    Array = '',
    Boolean = '',
    Class = '',
    Color = '',
    Constant = '',
    Constructor = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '',
    Function = '',
    Interface = '',
    Key = '',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '',
    Null = 'ﳠ',
    Number = '',
    Object = '',
    Operator = '',
    Package = '',
    Property = '',
    Reference = '',
    Snippet = '',
    String = '',
    Struct = '',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',
    Copilot = '',
    TabNine = '⌬',
  },
  --
  git = {
    LineAdded = '',
    LineModified = '',
    LineRemoved = '',
    FileDeleted = '',
    FileIgnored = '◌',
    FileRenamed = '',
    FileStaged = '✓',
    FileUnmerged = '',
    FileUnstaged = '',
    FileUntracked = '★',
    Diff = '',
    Repo = '',
    Octoface = '',
    Branch = '',
  },
  --
  lazy = {
    ft = '',
    source = '',
    lazy = '󰂠',
    loaded = '',
    not_loaded = '',
    require = '',
    cmd = '⌘',
    init = '⚙',
    config = '',
    event = '',
    keys = '',
    plugin = '',
    runtime = '',
    start = '',
    task = '',
  },
  --
  border = {
    '┏',
    '━',
    '┓',
    '┃',
    '┛',
    '━',
    '┗',
    '┃',
  },
  --
  misc = {
    Robot = 'ﮧ',
    Squirrel = '',
    Tag = '',
    Watch = '',
    Smiley = '',
    Package = '',
    CircuitBoard = '',
    LualineFmt = '',
  },
  --
  nvtree_chad = {
    default = '󰈚',
    symlink = '',
    folder = {
      default = '',
      empty = '',
      empty_open = '',
      open = '',
      symlink = '',
      symlink_open = '',
      arrow_open = '',
      arrow_closed = '',
    },
  },
  text = {
    ActiveLSP = 'LSP:',
    ArrowLeft = '<',
    ArrowRight = '>',
    BufferClose = 'x',
    DapBreakpoint = 'B',
    DapBreakpointCondition = 'C',
    DapBreakpointRejected = 'R',
    DapLogPoint = 'L',
    DapStopped = '>',
    DefaultFile = '[F]',
    DiagnosticError = 'X',
    DiagnosticHint = '?',
    DiagnosticInfo = 'i',
    DiagnosticWarn = '!',
    Ellipsis = '...',
    Environment = 'Env:',
    FileModified = '*',
    FileReadOnly = '[lock]',
    FoldClosed = '+',
    FoldOpened = '-',
    FoldSeparator = ' ',
    FolderClosed = '[D]',
    FolderEmpty = '[E]',
    FolderOpen = '[O]',
    GitAdd = '[+]',
    GitChange = '[/]',
    GitConflict = '[!]',
    GitDelete = '[-]',
    GitIgnored = '[I]',
    GitRenamed = '[R]',
    GitStaged = '[S]',
    GitUnstaged = '[U]',
    GitUntracked = '[?]',
    MacroRecording = 'Recording:',
    Paste = '[PASTE]',
    Search = '?',
    Selected = '*',
    Spellcheck = '[SPELL]',
    TabClose = 'X',
  },
}
