-- lua/core/ascii.lua

return {
  -- Which-key
  Debugger = '',
  Run = '󰑮',
  Find = '',
  Session = '󱂬',
  Sort = '󰒺',
  Buffer = '󰓩',
  Terminal = '',
  UI = '',
  Test = '󰙨',
  Packages = '󰏖',
  Docs = '',
  Git = '󰊢',
  LSP = '',

  -- Heirline-components - tabline
  BufferClose = '󰅖',
  FileModified = '',
  FileReadOnly = '',
  ArrowLeft = '',
  ArrowRight = '',
  TabClose = '󰅙',

  -- Heirline-components - winbar
  CompilerPlay = '',
  CompilerStop = '',
  CompilerRedo = '',
  NeoTree = '',
  Aerial = '',
  ZenMode = '󰰶',
  BufWrite = '',
  BufWriteAll = '',
  Ellipsis = '…',
  BreadcrumbSeparator = '',

  -- Heirline-components - statuscolumn
  FoldClosed = '',
  FoldOpened = '',
  FoldSeparator = ' ',

  -- Heirline-components - statusline
  ActiveLSP = '',
  ActiveTS = '',
  Environment = '',
  DiagnosticError = '',
  DiagnosticErrorBold = '',
  DiagnosticHint = '',
  DiagnosticHintBold = '󰌵',
  DiagnosticInfo = '',
  DiagnosticInfoBold = '󰋼',
  DiagnosticWarn = '',
  DiagnosticWarnBold = '',
  Question = '',
  BoldQuestion = '',
  LSPLoading1 = '',
  LSPLoading2 = '󰀚',
  LSPLoading3 = '',
  SearchCount = '',
  MacroRecording = '',
  ToggleResults = '󰑮',
  Debug = '',
  Trace = '✎',

  -- Heirline-components - misc
  Paste = '󰅌',
  PathSeparator = '',

  -- Neotree
  FolderClosed = '',
  FolderEmpty = '',
  FolderOpen = '',
  Diagnostic = '󰒡',
  DefaultFile = '󰈙',
  Symlink = '',

  -- Git
  GitBranch = '',
  GitAdd = '',
  GitChange = '',
  GitDelete = '',
  GitConflict = '',
  GitIgnored = '◌',
  GitRenamed = '➜',
  GitSign = '▎',
  GitUnmerged = "",
  GitStaged = '✓',
  GitUnstaged = '✗',
  GitUntracked = '★',
  GitDiff = '',
  GitRepo = '',
  GitOctoface = '',
  GitLineAdded = '',
  GitLineModified = '',
  GitModified = "",
  GitLineRemoved = '',

  -- DAP
  DapBreakpoint = '',
  DapBreakpointCondition = '',
  DapBreakpointRejected = '',
  DapLogPoint = '.>',
  DapStopped = '󰁕',

  -- Telescope
  PromptPrefix = '❯',

  -- Nvim-lightbulb
  Lightbulb = '💡',

  -- Alpha
  GreeterNew = '📄',
  GreeterRecent = '🌺',
  GreeterYazi = '🦆',
  GreeterSessions = '🔎',
  GreeterProjects = '💼',
  GreeterPlug = '',

  -- Mason
  MasonInstalled = '✓',
  MasonUninstalled = '✗',
  MasonPending = '⟳',

  -- Kind
  Array = '',
  Boolean = '',
  Class = '',
  Color = '',
  Constant = '',
  Constructor = '',
  Enum = '',
  EnumMember = '',
  Event = '',
  Field = '',
  File = '',
  Folder = '',
  Function = '',
  Interface = '',
  Key = '',
  Keyword = '',
  Method = '',
  Module = '',
  Namespace = '',
  Null = 'ﳠ',
  Number = '',
  Object = '',
  Operator = '',
  Property = '',
  Reference = '',
  Snippet = '',
  String = '',
  Struct = '',
  Text = '',
  TypeParameter = '',
  Unit = '',
  Value = '',
  Variable = '',

  -- Lazy
  lazy = {
    ft = '',
    source = '',
    lazy = '󰂠',
    loaded = '',
    not_loaded = '',
    require = '',
    cmd = '⌘',
    init = '⚙',
    config = '',
    event = '',
    keys = '',
    plugin = '',
    runtime = '',
    start = '',
    task = '',
  },

  -- Files
  lua = '',
  markdown = '',
  ttf = '',
  robots = '󰚩',
  woff = '',
  woff2 = '',

  -- Misc
  Robot = 'ﮧ',
  BookMark = '',
  Bookmarks = '',
  Calendar = '',
  CloudDownload = '',
  Code = '',
  Comment = '',
  Dashboard = '',
  FileSymlink = '',
  List = '',
  Lock = '',
  Files = '',
  FindFile = '󰈞',
  FindText = '󱎸',
  FolderSymlink = '',
  Project = '',
  SignIn = '',
  SignOut = '',
  Stacks = '',
  Scopes = '',
  Table = '',
  Target = '󰀘',
  Telescope = '',
  Tab = '󰓩',
  Tree = '',
  Fire = '',
  Squirrel = '',
  Tag = '',
  Watch = '',
  Smiley = '',
  Window = '',
  WordFile = '󰈭',
  Package = '',
  CircuitBoard = '',
  LualineFmt = '',
  Copilot = '',
  TabNine = '⌬',

  -- Render-markdown
  RenderMarkdown = { ' ', ' ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },

  -- Border
  border = { '┏', '━', '┓', '┃', '┛', '━', '┗', '┃' },
}
